services:
  backend:
    image: my-app-backend
    container_name: my-app-backend
    restart: unless-stopped
    build:
      context: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - 4000:4000
  frontend:
    image: my-app-frontend
    container_name: my-app-frontend
    build:
      context: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
  nginx:
    image: nginx:1.20.1
    container_name: reverse-proxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend
