services:
  backend:
    image: todo-backend-dev
    container_name: todo-backend-dev
    restart: unless-stopped
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    ports:
      - 4000:4000
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - PORT=4000
    depends_on:
      - mongo
      - redis
  frontend:
    image: todo-frontend-dev
    container_name: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo:/data/db
  redis:
    image: redis
    container_name: 'redis'
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: ['redis-server', '--appendonly', 'yes']
  nginx:
    image: nginx:1.20.1
    container_name: reverse-proxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend
  debug-helper:
    image: busybox

volumes:
  mongo:
  redis:
